version = 0.1
[default.deploy.parameters]
stack_name = "stg"
resolve_s3 = true
s3_prefix = "stg"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
